# Generated by Django 6.0.6 on 2026-07-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
