# Generated by Django 6.0.6 on 2026-07-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_gallery_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='api.gallery'),
        ),
    ]
