# Generated by Django 6.0.6 on 2026-07-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_gallery_recommendations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='event_type',
        ),
        migrations.AddField(
            model_name='contactenquiry',
            name='services_required',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='phone',
            field=models.CharField(default='', max_length=20),
        ),
    ]
